[package]
name = "rtoml"
version = "0.0.3"
edition = "2021"

[dependencies]
toml_edit = "0.19.8"
rutils =  { version ="0.0.1", path="../rutils" }

[lib]
name = "rtoml"
crate-type = ["cdylib", "staticlib"]