[package]
name = "rtoml"
version = "0.0.3"
edition = "2021"

[dependencies]
toml_edit = { version = "0.19.14" }

funny-utils-rs = { git = "https://git.sofunny.io/devtools/libs/funny-utils-rs", rev = "1d79aa972d48aff" }

[lib]
name = "rtoml"
crate-type = ["cdylib", "staticlib"]