[package]
name = "rtoml"
version = "0.0.3"
edition = "2021"

[dependencies]
toml_edit = "0.19.8"

funny-utils-rs = { git = "https://git.sofunny.io/devtools/libs/funny-utils-rs", tag = "0.1.1" }

[lib]
name = "rtoml"
crate-type = ["cdylib", "staticlib"]